### ISSUE TITLE
Student is registered twice for same employee

### ISSUE THREAD

**Issue by SarvagyaGupta** [Elegant-Queueing/q-backend#17]
What should happen in Firebase if the student has talked to the employee twice and employee acknowledges it? Do we add the student twice? Do we not register the student again?

**Comment by rtldr** [comment]
I don't think we should let them talk twice. We can allow the employee to edit / add tags after they're done talking to a student - and that would be another update API that we'd have to implement.

**Comment by rtldr** [comment]
However, it might make sense for a student to want to talk to an employee again. In that case, we should allow them to talk (join queue, join employee queue etc.) for the same employee; but we shouldn't register the talk twice. On the employee's app, we should probably show the registered association - meaning show the tags that were added previously. Maybe add an alert as well, saying that the student already talked.
