### ISSUE TITLE
Updating employees a student has talked to

### ISSUE THREAD

**Issue by amankagarwal** [Elegant-Queueing/q-backend#40]
Should not be able to add employee a student has talked to using the same API currently

**Comment by SarvagyaGupta** [comment]
There should be no way to update this from the student side

**Comment by SarvagyaGupta** [comment]
Never update this

**Comment by amankagarwal** [comment]
Should have phrased it differently- current implementation allows to make an API update call and set employee to null or anything- which is wrong. Need a fix for that

**Comment by SarvagyaGupta** [comment]
I think this issue is a subproblem of #28 where we need to find out what we exactly need from front end and what we need to send to the front end

**Comment by SarvagyaGupta** [comment]
I would prefer to have another set of models that interact with the front end, even if they are a copy of the db or redis models. It does not seem like a good design to send a redis or a database object back to the front end

**Comment by amankagarwal** [comment]
Agree on the idea of having another model to interact with front-end- with the current methodology we have fields like email/university-id/employees that could be mapped as well, which is bad.

**Comment by amankagarwal** [comment]
resolved this by using @exclude tag- there is no way update/add API can now add random employees field or change the current employees field (request and response object do not have employees field either, so JsonIgnoreProperties(unknown = true) takes care if someone tries to pass an employees field to the request).
