### ISSUE TITLE
Can't find q-public-ami EC2 image

### ISSUE THREAD

**Issue by sweekruthi** [Elegant-Queueing/q-backend#55]
**Describe the bug**
I tried searching for the q-public-ami AMI with the filter being Public images. There were 0 results.

**To Reproduce**
1. create an account on AWS and sign in
2. Click on Services (top left) and select EC2. If you can't find EC2, search for it and it should show up.
3. Click on AMI. It should be on the left panel, under 'Images'.
4. Next to the search bar, should be a filter saying 'Owned by me'. Change that to public images.
5. Search for q-public-ami and press enter.
6. Select the AMI and click on Launch.

**Expected behavior**
I expected the AMI to show up

**Screenshots**
![image](https://user-images.githubusercontent.com/64812367/82764846-e3d9ab00-9dc6-11ea-97d5-e9fff834220a.png)

**Comment by rtldr** [comment]
Hey, try changing your location from Ohio to Oregon (top right). Let me know if it shows up once you do that.

I'll add the part about location to the Readme.

Thanks!
