### ISSUE TITLE
Issues running/using API after following README instructions

### ISSUE THREAD

**Issue by andrewcalimlim** [Elegant-Queueing/q-backend#57]
**Describe the bug**

README.md > Developer Documentation > Firebase 
Following the tutorial for own database, the placement of the Schema file is not specified.

README.md > User documentation > Using the APIs > 

> Just for a sanity check, run the the app and do the following:

> Enter the following URI and make a GET API call to {address}:8080/employee/get/employee-id/{employee_id} Replace the {address} with localhost or your public DNS. Replace the {employee_id} with the id of an employee that you created when you added a document in the employees collection.

I don't know what a GET API call is nor where I should be typing the "{address}:8080/employee/get/employee-id/{employee_id}" call, but typing it in the redis-server terminal window, spring boot terminal window, or a new terminal window either hangs and awaits more input (redis/spring windows) or `-bash: {localhost}:8080/employee/get/employee-id/989YTW6EmotAQGxIzq0A: No such file or directory` (new terminal window)

**To Reproduce**
My database url is `https://bruh-c0223.firebaseio.com`

**Expected behavior**
The sanity check output listed in the file, aka:

`{
    "employee": {
        "employee_id": "bfkE7Q0k9obASshNApN3",
        "name": "John Doe",
        "company_id": "A51NaN8uB9GEViJZHbuo",
        "role": "SWE",
        "bio": "I code. A lot",
        "email": "codealot@code.com",
        "students": [
            "oFEdwg9lnWPPVjHPL0Nk"
        ]
    }
}`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Version: Master

**Comment by SarvagyaGupta** [comment]
Hi Andrew,

You should be using Postman to run the APIs. If you don't have postman or are having trouble downloading it in your local machine, use `curl --request GET '{address}:8080/employee/get/employee-id/989YTW6EmotAQGxIzq0A'` to get command running.

Sorry for the delayed response.
